run:
  timeout: 5m
  modules-download-mode: readonly
  go: '1.21'

linters:
  enable:
    # Basic linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Style and formatting
    - gofmt
    - goimports
    - gocritic
    - revive
    
    # Potential bugs
    - bodyclose
    - gosec
    - goconst
    - dupl
    - unconvert
    - misspell
    
    # Performance
    - prealloc
    
    # Complexity
    - gocyclo
    - funlen
    - nestif
    
    # Comments and documentation
    - godot
    - godox
    
    # Error handling
    - errorlint
    - wrapcheck
    
  disable:
    - exhaustruct  # Too strict for our use case
    - varnamelen   # Variable names can be short in some contexts
    - nlreturn     # Too opinionated about line returns
    - wsl          # Too many whitespace rules
    - lll          # Line length handled by gofmt

linters-settings:
  gocyclo:
    min-complexity: 15
    
  funlen:
    lines: 100
    statements: 50
    
  govet:
    enable-all: true
    disable:
      - shadow  # Can be useful but often triggers false positives
      
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G304  # File path from variable - we validate paths in our code
      
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - unnamedResult  # Named returns can be less clear sometimes
      - whyNoLint     # We'll use nolint comments when needed
      
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
          
  errorlint:
    errorf: true
    asserts: true
    comparison: true
    
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
    ignorePackageGlobs:
      - encoding/*
      - github.com/pkg/*

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        
    # Disable some rules for generated files
    - path: ".*\\.pb\\.go$"
      linters:
        - all
        
    # Allow long lines in generated code
    - path: templates\.go
      linters:
        - all
        
    # Ignore complexity in main.go and cmd files
    - path: "cmd/"
      linters:
        - gocyclo
        - funlen
        
    # Ignore some issues in test utilities
    - path: "test/"
      linters:
        - gocyclo
        - funlen
        - dupl
        
  max-issues-per-linter: 0
  max-same-issues: 0
  
severity:
  default-severity: error
  
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true