name: Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

permissions:
  contents: write
  id-token: write  # For PyPI trusted publishing

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for setuptools-scm
          ref: ${{ github.ref }}  # Ensure we checkout the actual tag

      - name: Extract version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Create dist directory
        run: mkdir -p dist

      - name: Build binaries with version info
        run: |
          # Extract version from tag (remove 'v' prefix for internal use, keep for git tag)
          VERSION=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')
          GIT_COMMIT=$(git rev-parse --short HEAD)
          BUILD_DATE=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          
          echo "Building with:"
          echo "  Version: $VERSION"
          echo "  Commit: $GIT_COMMIT"
          echo "  Build Date: $BUILD_DATE"
          
          # Build with ldflags to embed version information
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X github.com/Pradyothsp/pyinit/internal/version.Version=$VERSION -X github.com/Pradyothsp/pyinit/internal/version.GitCommit=$GIT_COMMIT -X 'github.com/Pradyothsp/pyinit/internal/version.BuildDate=$BUILD_DATE'" -o dist/pyinit-darwin-amd64 ./cmd/pyinit
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X github.com/Pradyothsp/pyinit/internal/version.Version=$VERSION -X github.com/Pradyothsp/pyinit/internal/version.GitCommit=$GIT_COMMIT -X 'github.com/Pradyothsp/pyinit/internal/version.BuildDate=$BUILD_DATE'" -o dist/pyinit-darwin-arm64 ./cmd/pyinit
          GOOS=linux GOARCH=amd64 go build -ldflags "-X github.com/Pradyothsp/pyinit/internal/version.Version=$VERSION -X github.com/Pradyothsp/pyinit/internal/version.GitCommit=$GIT_COMMIT -X 'github.com/Pradyothsp/pyinit/internal/version.BuildDate=$BUILD_DATE'" -o dist/pyinit-linux-amd64 ./cmd/pyinit
          GOOS=windows GOARCH=amd64 go build -ldflags "-X github.com/Pradyothsp/pyinit/internal/version.Version=$VERSION -X github.com/Pradyothsp/pyinit/internal/version.GitCommit=$GIT_COMMIT -X 'github.com/Pradyothsp/pyinit/internal/version.BuildDate=$BUILD_DATE'" -o dist/pyinit-windows-amd64.exe ./cmd/pyinit
          
          # Copy binaries to root for backwards compatibility with release step
          cp dist/* ./

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: |
            pyinit-darwin-amd64
            pyinit-darwin-arm64
            pyinit-linux-amd64
            pyinit-windows-amd64.exe

  publish-python-package:
    needs: build-and-release
    runs-on: ubuntu-latest
    environment: PyPI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for setuptools-scm

      - name: Wait for release assets
        run: |
          echo "Waiting 30 seconds for release assets to be available..."
          sleep 30

      - name: Update Python package checksums
        run: |
          VERSION="${{ needs.build-and-release.outputs.version }}"
          echo "Updating checksums for version: $VERSION"
          
          # Download the released binaries (need v prefix for GitHub releases)
          curl -L -f -o pyinit-darwin-amd64 "https://github.com/Pradyothsp/pyinit/releases/download/v$VERSION/pyinit-darwin-amd64"
          curl -L -f -o pyinit-darwin-arm64 "https://github.com/Pradyothsp/pyinit/releases/download/v$VERSION/pyinit-darwin-arm64"
          curl -L -f -o pyinit-linux-amd64 "https://github.com/Pradyothsp/pyinit/releases/download/v$VERSION/pyinit-linux-amd64"
          curl -L -f -o pyinit-windows-amd64.exe "https://github.com/Pradyothsp/pyinit/releases/download/v$VERSION/pyinit-windows-amd64.exe"
          
          # Calculate checksums
          DARWIN_AMD64_SHA=$(sha256sum pyinit-darwin-amd64 | cut -d' ' -f1)
          DARWIN_ARM64_SHA=$(sha256sum pyinit-darwin-arm64 | cut -d' ' -f1)
          LINUX_AMD64_SHA=$(sha256sum pyinit-linux-amd64 | cut -d' ' -f1)
          WINDOWS_AMD64_SHA=$(sha256sum pyinit-windows-amd64.exe | cut -d' ' -f1)
          
          echo "Checksums:"
          echo "  Darwin AMD64:  $DARWIN_AMD64_SHA"
          echo "  Darwin ARM64:  $DARWIN_ARM64_SHA"
          echo "  Linux AMD64:   $LINUX_AMD64_SHA"
          echo "  Windows AMD64: $WINDOWS_AMD64_SHA"
          
          # Update downloader.py with new checksums using awk
          awk -v version="$VERSION" -v amd64="$DARWIN_AMD64_SHA" -v arm64="$DARWIN_ARM64_SHA" -v linux="$LINUX_AMD64_SHA" -v windows="$WINDOWS_AMD64_SHA" '
          /^    }$/ && !added {
              printf "        \"%s\": {\n", version
              printf "            \"darwin-amd64\": \"%s\",\n", amd64
              printf "            \"darwin-arm64\": \"%s\",\n", arm64
              printf "            \"linux-amd64\": \"%s\",\n", linux
              printf "            \"windows-amd64\": \"%s\",\n", windows
              printf "        },\n"
              added = 1
          }
          { print }
          ' python-package/pyinit_cli/downloader.py > temp_downloader.py
          mv temp_downloader.py python-package/pyinit_cli/downloader.py

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools-scm

      - name: Debug Git and version info
        run: |
          cd python-package
          echo "Current git status:"
          git status
          echo "Git tags:"
          git tag -l
          echo "Current ref: ${{ github.ref }}"
          echo "Setuptools-scm version detection:"
          python -m setuptools_scm || echo "setuptools-scm not yet installed"

      - name: Build Python package
        run: |
          cd python-package
          # Force setuptools-scm to use the correct version
          export SETUPTOOLS_SCM_PRETEND_VERSION="${{ needs.build-and-release.outputs.version }}"
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python-package/dist/

      # Note: We skip committing checksums back since they're used for the current build
      # The checksums will be available in the published package

  trigger-homebrew-update:
    needs: build-and-release
    runs-on: ubuntu-latest
    environment: Homebrew
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Trigger Homebrew formula update
        run: |
          echo "Creating JSON payload..."
          JSON_PAYLOAD=$(jq -n \
            --arg version "v${{ needs.build-and-release.outputs.version }}" \
            --arg repo "${{ github.repository }}" \
            '{event_type: "new-release", client_payload: {version: $version, repository: $repo}}')
          
          echo "JSON Payload: $JSON_PAYLOAD"
          
          echo "Sending webhook..."
          HTTP_CODE=$(curl -w "%{http_code}" -o /tmp/response.txt \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.HOMEBREW_UPDATE_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Pradyothsp/homebrew-pyinit/dispatches \
            -d "$JSON_PAYLOAD")
          
          echo "HTTP Code: $HTTP_CODE"
          echo "Response Body:"
          cat /tmp/response.txt
          
          if [ "$HTTP_CODE" != "204" ]; then
            echo "Webhook failed with code: $HTTP_CODE"
            exit 1
          else
            echo "Webhook sent successfully!"
          fi