name: Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binaries
        run: |
          GOOS=darwin GOARCH=amd64 go build -o pyinit-darwin-amd64 ./cmd/pyinit
          GOOS=darwin GOARCH=arm64 go build -o pyinit-darwin-arm64 ./cmd/pyinit
          GOOS=linux GOARCH=amd64 go build -o pyinit-linux-amd64 ./cmd/pyinit

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            pyinit-darwin-amd64
            pyinit-darwin-arm64
            pyinit-linux-amd64