name: Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binaries
        run: |
          GOOS=darwin GOARCH=amd64 go build -o pyinit-darwin-amd64 ./cmd/pyinit
          GOOS=darwin GOARCH=arm64 go build -o pyinit-darwin-arm64 ./cmd/pyinit
          GOOS=linux GOARCH=amd64 go build -o pyinit-linux-amd64 ./cmd/pyinit

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: |
            pyinit-darwin-amd64
            pyinit-darwin-arm64
            pyinit-linux-amd64

  trigger-homebrew-update:
    needs: build-and-release
    runs-on: ubuntu-latest
    environment: Prod
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Trigger Homebrew formula update
        run: |
          echo "Creating JSON payload..."
          JSON_PAYLOAD=$(jq -n \
            --arg version "${{ github.ref_name }}" \
            --arg repo "${{ github.repository }}" \
            '{event_type: "new-release", client_payload: {version: $version, repository: $repo}}')
          
          echo "JSON Payload: $JSON_PAYLOAD"
          
          echo "Sending webhook..."
          HTTP_CODE=$(curl -w "%{http_code}" -o /tmp/response.txt \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.HOMEBREW_UPDATE_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Pradyothsp/homebrew-pyinit/dispatches \
            -d "$JSON_PAYLOAD")
          
          echo "HTTP Code: $HTTP_CODE"
          echo "Response Body:"
          cat /tmp/response.txt
          
          if [ "$HTTP_CODE" != "204" ]; then
            echo "Webhook failed with code: $HTTP_CODE"
            exit 1
          else
            echo "Webhook sent successfully!"
          fi